name: FrontendPipeline
trigger:
  - main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python39:
      python.version: "3.9"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(python.version)"
    displayName: "Use Python $(python.version)"

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install dependencies"

  - task: Docker@2
    displayName: "Build and push Docker image"
    inputs:
      containerRegistry: "DockerHub"
      repository: "abdulalikhan/devops-frontend"
      command: "buildAndPush"
      Dockerfile: "**/Dockerfile"
      tags: "$(Build.BuildId)"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true
    displayName: "Archive files"

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: "frontend"
      pathToPublish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
